server:
  port: ${AUTHENTICATION_SERVICE_PORT:9527}

# Database properties
spring:
  datasource:
    driverClassName: ${DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    platform: mysql
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_SERVER_PORT:3306}/${DB_NAME:knowledge_hub_db}?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    database: MYSQL
    show-sql: true
    # set generate-ddl as false before pushing to production
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_schema: REPLACE_SCHEMA_NAME
        # Set the ddl-auto to none before pushing to production.
        #ddl-auto: none
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

# Information that gets displayed in the spring admin UI
# ------------------------------------------------------
info:
  app:
    name: ${spring.application.name}
    description: Authentication Service for application.