server:
  port: 9485

# Database properties
spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/knowledge_hub_db?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    database: MYSQL
    show-sql: true
    # set generate-ddl as false before pushing to production
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: knowledge_hub_schema
        # Set the ddl-auto to none before pushing to production.
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
# API Documentation settings
com.knowledge.hub.configuration:
  security:
    auth:
      validate-token-url:
        url: http://localhost:8762/validateToken

# Information that gets displayed in the spring admin UI
# ------------------------------------------------------
info:
  app:
    name: knowledgehub-knowledgehub-service
    description: This is a tutorials website
